source "https://rubygems.org"

# gem "solargraph", "~> 0.49.0", :group => :development

# gem 'sorbet', :group => :development
# gem 'sorbet-runtime'
# gem "tapioca", require: false, :group => :development
